import { JobDetailView } from '@/features/jobs/components/JobDetailView';

/**
 * `params` is a Promise in Next 16, so this has to be async. `PageProps` is
 * generated by `next dev` / `next build` / `next typegen` and is global — no
 * import needed. Same shape as `/roles/[roleId]`.
 *
 * The raw segment is passed straight through: `JobDetailView` decides whether
 * it's a valid id, since it's the component that renders the answer if it isn't.
 */
export default async function JobPage(props: PageProps<'/jobs/[jobId]'>) {
  const { jobId } = await props.params;

  return <JobDetailView jobId={jobId} />;
}
