import { RoleDetailView } from '@/features/roles/components/RoleDetailView';

/**
 * `params` is a Promise in Next 16, so this has to be async. `PageProps` is
 * generated by `next dev` / `next build` / `next typegen` and is global — no
 * import needed.
 *
 * The raw segment is passed straight through: `RoleDetailView` decides whether
 * it's a valid id, since it's the component that renders the answer if it
 * isn't.
 */
export default async function RolePage(props: PageProps<'/roles/[roleId]'>) {
  const { roleId } = await props.params;

  return <RoleDetailView roleId={roleId} />;
}
