import { CandidateDetailView } from '@/features/candidates/components/CandidateDetailView';

/**
 * `params` is a Promise in Next 16, so this has to be async. `PageProps` is
 * generated by `next dev` / `next build` / `next typegen` and is global — no
 * import needed.
 *
 * The raw segment is passed straight through: `CandidateDetailView` decides
 * whether it is a valid id, since it is the component that renders the answer
 * if it is not (FE-9).
 */
export default async function CandidatePage(props: PageProps<'/candidates/[candidateId]'>) {
  const { candidateId } = await props.params;

  return <CandidateDetailView candidateId={candidateId} />;
}
