import { InterviewDetailDispatch } from '@/features/interviews/components/InterviewDetailDispatch';

/**
 * One round, for either privileged role.
 *
 * `params` is a Promise in Next 16, so this has to be async. `PageProps` is
 * generated by `next dev` / `next build` / `next typegen` and is global — no
 * import needed.
 *
 * The raw segment is passed straight through: the component below decides
 * whether it is a valid id, since it is the one that renders the answer if it
 * is not. Which of the two detail components runs is a client-side decision on
 * the signed-in role, so it lives in `InterviewDetailDispatch` rather than here
 * — this file cannot read `useAuth()`.
 */
export default async function InterviewPage(props: PageProps<'/interviews/[interviewId]'>) {
  const { interviewId } = await props.params;

  return <InterviewDetailDispatch interviewId={interviewId} />;
}
